If a function never returns to the caller, don't create return edges, e.g. in the following case:
void f() {
ERROR: goto ERROR;
// not reachable due to endless loop
}

void main() {
        f();
        int x;
}

The edges after the function call (here: "int x;") are removed from the CFA.
The summary edge connecting the call-site node and it's successor is left in the CFA because some parts rely on it.

git-svn-id: https://svn.sosy-lab.org/software/cpachecker/trunk@2766 4712c6d2-40bb-43ae-aa4b-fec3f1bdfe4c